### DISCUSSION TITLE
Can the doc parameter and reference field be shown in documentation?

### DISCUSSION THREAD

**Discussion by wigging** [watertap-org/watertap#969] [Q&A]
For the zero-order models, there is `doc` parameter defined for variables such as

```python
self.electrode_width = Var(
    initialize=1,
    bounds=(0, None),
    units=pyunits.m,
    doc="Electrode width"
)
```

And in the YAML files associated with these zero-order models, there is a `reference` field that can be defined such as

```yaml
ec_admin_lab_op_exp:
  value: 0.4589
  units: dimensionless
  reference: Sharma (2010) - doi.org/10.1016/j.envadv.2020.100029 
```

How do I get the information in these `doc` parameters and `reference` fields to be rendered by Sphinx for the documentation of these models? Or is there another way that a user can view these docs and references?
