### ISSUE TITLE
Database does not utilize path to user provided YAML file

### ISSUE THREAD

**Issue by wigging** [watertap-org/watertap#907]
### Description

The `dbpath` parameter for the `Database` class is supposed to let the user define the path to a YAML file. But this path is ignored and watertap uses the database YAML files provided in watertap which are located at `watertap/data/techno_economic/`.

```python
from pyomo.environ import ConcreteModel
from watertap.core.wt_database import Database

model = ConcreteModel()
model.db = Database(dbpath=".")
``` 

### Expected Behavior

When the user provides the path to a YAML file with `Database(dbpath="path/to/myfile.yaml")`, then the model should use the parameters defined in that file.

### Steps to Reproduce

Parameters for a zero-order model are defined in the YAML file shown below.

```yaml
default:
  energy_electric_flow_vol_inlet:
    value: 0.050718512
    units: kWh/m^3
  capital_cost:
    basis: flow_vol
    cost_factor: None
    reference_state:
      value: 4732.0
      units: m^3/hr
    capital_a_parameter:
      value: 12.17829669e6
      units: USD_2014
    capital_b_parameter:
      value: 0.5862
      units: dimensionless
  recovery_frac_mass_H2O:
    value: 0.99
    units: dimensionless
    reference:
  default_removal_frac_mass_comp:
    value: 0
    units: dimensionless
  removal_frac_mass_comp:
    nonvolatile_toc:
      value: 0.2
      units: dimensionless
      constituent_longform: Nonvolatile TOC
    toc:
      value: 0.2
      units: dimensionless
      constituent_longform: Total Organic Carbon (TOC)
    tss:
      value: 0.97
      units: dimensionless
      constituent_longform: Total Suspended Solids (TSS)
```

The YAML file is located in the same directory as the example shown below.

```python
from pyomo.environ import ConcreteModel
from idaes.core import FlowsheetBlock
from idaes.core.solvers import get_solver
from watertap.core.wt_database import Database
from watertap.core.zero_order_properties import WaterParameterBlock
from watertap.unit_models.zero_order import DualMediaFiltrationZO

def main():

    model = ConcreteModel()
    model.db = Database(dbpath=".")

    model.fs = FlowsheetBlock(dynamic=False)
    model.fs.params = WaterParameterBlock(solute_list=["nonvolatile_toc", "toc", "tss"])

    model.fs.unit = DualMediaFiltrationZO(property_package=model.fs.params, database=model.db)
    model.fs.unit.inlet.flow_mass_comp[0, "H2O"].fix(10)
    model.fs.unit.inlet.flow_mass_comp[0, "nonvolatile_toc"].fix(1)
    model.fs.unit.inlet.flow_mass_comp[0, "toc"].fix(1)
    model.fs.unit.inlet.flow_mass_comp[0, "tss"].fix(1)

    _ = model.db.get_unit_operation_parameters("dual_media_filter")
    model.fs.unit.load_parameters_from_database()

    solver = get_solver()
    solver.solve(model)

    model.fs.unit.report()

if __name__ == "__main__":
    main()
```

Running this example gives the error shown here.

```
$ python dual_media_filter.py

Traceback (most recent call last):
  File "/Users/g72/Desktop/ORNL/WaterTAP/watertap/watertap/core/wt_database.py", line 201, in _get_technology
    with open(os.path.join(self._dbpath, technology + ".yaml"), "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './dual_media_filtration.yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dual_media_filter.py", line 49, in <module>
    main()
  File "dual_media_filter.py", line 40, in main
    model.fs.unit.load_parameters_from_database()
  File "/Users/g72/Desktop/ORNL/WaterTAP/watertap/watertap/core/zero_order_base.py", line 192, in load_parameters_from_database
    pdict = self.config.database.get_unit_operation_parameters(
  File "/Users/g72/Desktop/ORNL/WaterTAP/watertap/watertap/core/wt_database.py", line 141, in get_unit_operation_parameters
    params = self._get_technology(technology)
  File "/Users/g72/Desktop/ORNL/WaterTAP/watertap/watertap/core/wt_database.py", line 205, in _get_technology
    raise KeyError(f"Could not find entry for {technology} in database.")
KeyError: 'Could not find entry for dual_media_filtration in database.'
```

To fix the example, you must set the private variable `_tech_type` to the name of the YAML file. This is shown in the edited example below.

```python
from pyomo.environ import ConcreteModel
from idaes.core import FlowsheetBlock
from idaes.core.solvers import get_solver
from watertap.core.wt_database import Database
from watertap.core.zero_order_properties import WaterParameterBlock
from watertap.unit_models.zero_order import DualMediaFiltrationZO

def main():

    model = ConcreteModel()
    model.db = Database(dbpath=".")

    model.fs = FlowsheetBlock(dynamic=False)
    model.fs.params = WaterParameterBlock(solute_list=["nonvolatile_toc", "toc", "tss"])

    model.fs.unit = DualMediaFiltrationZO(property_package=model.fs.params, database=model.db)
    model.fs.unit.inlet.flow_mass_comp[0, "H2O"].fix(10)
    model.fs.unit.inlet.flow_mass_comp[0, "nonvolatile_toc"].fix(1)
    model.fs.unit.inlet.flow_mass_comp[0, "toc"].fix(1)
    model.fs.unit.inlet.flow_mass_comp[0, "tss"].fix(1)

    # This example only works if the following line is uncommented
    model.fs.unit._tech_type = "dual_media_filter"

    _ = model.db.get_unit_operation_parameters("dual_media_filter")
    model.fs.unit.load_parameters_from_database()

    solver = get_solver()
    solver.solve(model)

    model.fs.unit.report()

if __name__ == "__main__":
    main()
```

Output from the edited example is here.

```
$ python dual_media_filter.py

====================================================================================
Unit : fs.unit                                                             Time: 0.0
------------------------------------------------------------------------------------
    Unit Performance

    Variables: 

    Key                              : Value      : Units         : Fixed : Bounds
                  Electricity Demand :     2373.6 :          watt : False : (0, None)
               Electricity Intensity : 1.8259e+05 :        pascal :  True : (None, None)
    Solute Removal [nonvolatile_toc] :    0.20000 : dimensionless :  True : (0, None)
                Solute Removal [toc] :    0.20000 : dimensionless :  True : (0, None)
                Solute Removal [tss] :    0.97000 : dimensionless :  True : (0, None)
                      Water Recovery :    0.99000 : dimensionless :  True : (0.0, 1.0000001)

------------------------------------------------------------------------------------
    Stream Table
                                               Units            Inlet   Treated  Byproduct
    Volumetric Flowrate                   meter ** 3 / second 0.013000 0.011530 0.0014700 
    Mass Concentration H2O              kilogram / meter ** 3   769.23   858.63    68.027 
    Mass Concentration nonvolatile_toc  kilogram / meter ** 3   76.923   69.384    136.05 
    Mass Concentration toc              kilogram / meter ** 3   76.923   69.384    136.05 
    Mass Concentration tss              kilogram / meter ** 3   76.923   2.6019    659.86 
====================================================================================
```

### Environment

- OS: macOS 12.6.2
- Python: v3.8.15
- WaterTAP: v0.8.dev0

### Anything Else?

I think the issue is caused by `_tech_type`. It seems to be hard coded to use the files located in `watertap/data/techno_economic/` directory. It is not being defined properly when `dbpath` is given for the `Database()`.
